import { BLUE, VIOLET, CYAN, EMERALD } from "@/lib/constants";

// ─── Chart Data ──────────────────────────────────────────────────────────────
export const lineData = [
  { month: "Jan", actual: 3.2, predicted: 2.9 },
  { month: "Feb", actual: 4.1, predicted: 3.8 },
  { month: "Mar", actual: 3.7, predicted: 4.0 },
  { month: "Apr", actual: 5.6, predicted: 5.1 },
  { month: "May", actual: 6.8, predicted: 6.5 },
  { month: "Jun", actual: 7.4, predicted: 7.2 },
  { month: "Jul", actual: 8.9, predicted: 8.5 },
  { month: "Aug", actual: 9.6, predicted: 9.3 },
];

export const barData = [
  { label: "NLP",      accuracy: 94, fill: BLUE   },
  { label: "Vision",   accuracy: 87, fill: VIOLET },
  { label: "Forecast", accuracy: 96, fill: BLUE   },
  { label: "Classify", accuracy: 81, fill: VIOLET },
  { label: "Extract",  accuracy: 88, fill: CYAN   },
];

export const kpiSparklines: Record<string, number[]> = {
  insights:    [18, 22, 19, 31, 28, 34, 29, 38, 41, 47],
  models:      [18, 18, 19, 20, 20, 21, 21, 22, 23, 23],
  sources:     [14, 14, 13, 13, 12, 13, 12, 12, 12, 12],
  automations: [3, 3, 4, 4, 5, 5, 5, 6, 7, 8],
};

// ─── Insights Table ───────────────────────────────────────────────────────────
export const recentInsights = [
  { id: "INS-0042", title: "Revenue anomaly detected in APAC region",           type: "Anomaly", severity: "critical", time: "2m ago",  delta: "−8.3%"  },
  { id: "INS-0041", title: "User retention +18% following v3.2 rollout",         type: "Trend",   severity: "positive", time: "14m ago", delta: "+18.1%" },
  { id: "INS-0040", title: "Inventory breach warning — SKU-7891 below threshold", type: "Alert",   severity: "high",     time: "1h ago",  delta: "−"      },
  { id: "INS-0039", title: "NLP confidence degraded on high-volume product SKUs", type: "Model",   severity: "medium",   time: "3h ago",  delta: "−4.2%"  },
  { id: "INS-0038", title: "Churn probability elevated for Enterprise cohort",    type: "Risk",    severity: "high",     time: "5h ago",  delta: "+6.7%"  },
];

// ─── Activity Feed ────────────────────────────────────────────────────────────
export type ActivityItem = {
  iconName: string;
  text: string;
  time: string;
  color: string;
  dot: string;
};

export const activityFeed: ActivityItem[] = [
  { iconName: "Sparkles",    text: "Q3 revenue forecast auto-generated by Atlas v2",  time: "Just now", color: "text-blue-400",    dot: BLUE    },
  { iconName: "Database",    text: "Salesforce CRM sync — 4,231 records updated",      time: "5m ago",   color: "text-emerald-400", dot: EMERALD },
  { iconName: "AlertCircle", text: "Churn model confidence below threshold: 76.4%",    time: "12m ago",  color: "text-amber-400",   dot: "#F59E0B" },
  { iconName: "GitBranch",   text: "Pipeline v3.1.0 deployed to production",           time: "38m ago",  color: "text-violet-400",  dot: VIOLET  },
  { iconName: "Check",       text: "Weekly digest delivered to 14 stakeholders",        time: "1h ago",   color: "text-white/30",    dot: "rgba(255,255,255,0.2)" },
];

// ─── Network Viz Data ─────────────────────────────────────────────────────────
export const networkNodes = [
  { x: 12, y: 15 }, { x: 32, y: 8  }, { x: 54, y: 14 }, { x: 78, y: 6  }, { x: 91, y: 22 },
  { x: 7,  y: 38 }, { x: 28, y: 34 }, { x: 50, y: 42 }, { x: 72, y: 30 }, { x: 93, y: 45 },
  { x: 16, y: 60 }, { x: 40, y: 68 }, { x: 62, y: 57 }, { x: 85, y: 65 }, { x: 50, y: 84 },
  { x: 23, y: 80 }, { x: 68, y: 80 },
];

export const networkEdges: [number, number][] = [
  [0,1],[1,2],[2,3],[3,4],[0,5],[1,6],[2,7],[3,8],[4,9],
  [5,6],[6,7],[7,8],[8,9],[5,10],[6,11],[7,12],[8,13],
  [10,11],[11,12],[12,13],[10,14],[11,14],[12,14],[13,14],
  [6,8],[1,7],[7,11],[2,8],[6,12],[10,15],[11,15],[12,16],[13,16],
];

export const hubNodes = new Set([7, 12, 6]);

// ─── Intelligence Flow Stages ─────────────────────────────────────────────────
export const flowStages = [
  {
    step: "01",
    iconName: "Database",
    title: "Ingest Data",
    description: "Connect any data source in minutes. Unify files, databases, and real-time streams in one pipeline.",
    color: "blue" as const,
    glowColor: BLUE,
    features: ["200+ native connectors", "CSV, JSON, Parquet upload", "Postgres, Snowflake, BigQuery", "Kafka, webhooks, REST APIs"],
    metric: { value: "200+", label: "Connectors available" },
  },
  {
    step: "02",
    iconName: "Brain",
    title: "Analyze with AI",
    description: "Foundation models process your data continuously — surfacing patterns, risks, and signals humans miss.",
    color: "violet" as const,
    glowColor: VIOLET,
    features: ["Anomaly & pattern detection", "Multi-class classification", "Time-series forecasting", "Entity & knowledge extraction"],
    metric: { value: "40+", label: "Foundation models" },
  },
  {
    step: "03",
    iconName: "Zap",
    title: "Generate Insight",
    description: "Intelligence surfaces as prioritized, actionable output — reports, live dashboards, or automated workflows.",
    color: "emerald" as const,
    glowColor: EMERALD,
    features: ["Auto-generated narratives", "Live insight dashboards", "Ranked recommendations", "No-code automations & alerts"],
    metric: { value: "< 2s", label: "Time to first insight" },
  },
];

// ─── API Endpoints ────────────────────────────────────────────────────────────
export const apiEndpoints = [
  { name: "REST API",  status: "operational" as const },
  { name: "GraphQL",   status: "operational" as const },
  { name: "Webhooks",  status: "operational" as const },
  { name: "WebSocket", status: "operational" as const },
];

// ─── Footer Links ─────────────────────────────────────────────────────────────
export const footerLinks = [
  { label: "Product",   items: ["Overview", "Data Sources", "AI Models", "Insights", "Automations", "API Reference"] },
  { label: "Company",   items: ["About", "Blog", "Careers", "Press", "Partners"] },
  { label: "Resources", items: ["Docs", "Changelog", "Status", "Community"] },
  { label: "Legal",     items: ["Privacy", "Terms", "Security", "Compliance", "DPA"] },
];
